### ISSUE TITLE
HtmlPreview approach is broken, but GitHub Pages will work

### ISSUE THREAD

**Issue by doctor-g** [Cakoluchiam/tsquest#1]
Routing the site through http://htmlpreview.github.io/?https://github.com/Cakoluchiam/tsquest/blob/master/thunderstone.html originally worked, but now it fails. The browser console shows errors regarding MIME types and jQuery. However, if you just push your code as-is to the `gh-pages` branch, then you can host it on GitHub Pages yourself directly, and it should work again. I have demonstrated this in my forked copy at https://doctor-g.github.io/tsquest/thunderstone.html.

**Comment by Cakoluchiam** [comment]
Thanks! I've moved to Pages and changed the original file to use an HTML redirect so folks don't have to update their bookmarks : )
